#modules
from Player import Player
from platform_object import Platform
from End import End
from tkinter import *
import time
import random
from portal import Portal
##import winsound
tk = Tk()
tk.title = ("Game")
tk.wm_attributes("-topmost", 1)
canvas = Canvas(tk, width=500, height=400)
my_image = PhotoImage(file='background_custom.gif')
canvas.create_image(0, 0, anchor = NW, image = my_image)

canvas.pack()
tk.update()

#The functions to load each lvl, they then update they player each frame and the player interacts with everything
def lvl1():
    platform = Platform(40, 20, 200, 25, canvas, "black")
    platform2 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform3 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform4 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform5 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform6 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform7 = Platform(10000, 20, 10001, 25, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    end = End(175, 26, 200, -10, canvas, 'blue', player)


    while True:
        player.draw()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            lvl2()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)

def lvl2():
    platform = Platform(20, 30, 100, 35, canvas, "black")
    platform2 = Platform(110, 0, 150, -5, canvas, "black")
    platform3 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform4 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform5 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform6 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform7 = Platform(10000, 20, 10001, 25, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    end = End(135, 0, 150, -36, canvas, 'blue', player)

    while True:
        player.draw()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            lvl3()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl3():
    platform = Platform(40, 50, 100, 55, canvas, "black")
    platform2 = Platform(10000, 0, 10001, -5, canvas, "black")
    platform3 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform4 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform5 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform6 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform7 = Platform(10000, 20, 10001, 25, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    lava = End(0, 100, 200, 200, canvas, 'red', player)
    end = End(210, 64, 225, 100, canvas, 'blue', player)

    while True:
        player.draw()
        if lava.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            lvl3()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            lvl4()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl4():
    platform = Platform(40, 50, 100, 55, canvas, "black")
    platform2 = Platform(110, -10, 170, -15, canvas, "black")
    platform3 = Platform(-30, -20, 20, -25, canvas, 'black')
    platform4 = Platform(40, -70, 100, -75, canvas, 'black')
    platform5 = Platform(40, -115, 100, -120, canvas, 'black')
    platform6 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform7 = Platform(10000, 20, 10001, 25, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    lava = End(40, -115, 100, -110, canvas, 'red', player)
    end = End(50, -151, 75, -115, canvas, 'blue', player)

    while True:
        player.draw()
        if lava.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            lvl5()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            lvl5()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl5():
    
    platform = Platform(-60, 40, 0, 45, canvas, "black")
    platform2 = Platform(10, -5, 70, -10, canvas, "black", 2, 0, 50)
    platform3 = Platform(200, -15, 350, -20, canvas, 'black')
    platform4 = Platform(10000, -70, 10000, -75, canvas, 'black')
    platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform6 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform7 = Platform(10000, 20, 10001, 25, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    lava = End(-40, 100, 300, 200, canvas, 'red', player)
    end = End(280, -18, 295, -59, canvas, 'blue', player)
    while True:
        player.draw()
        platform2.draw()
        if lava.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            lvl5()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            lvl6()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl6():
    platform = Platform(10000, -70, 10000, -75, canvas, 'black')
    platform2 = Platform(10000, -70, 10000, -75, canvas, 'black')
    platform3 = Platform(10000, -70, 10000, -75, canvas, 'black')
    platform4 = Platform(10000, -70, 10000, -75, canvas, 'black')
    platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform6 = Platform(10000, 20, 10001, 25, canvas, 'black')
    platform7 = Platform(10000, 20, 10001, 25, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    lava = End(-70, 110, -60, 70, canvas, 'red', player)
    lava2 = End(30, 110, 40, 70, canvas, 'red', player)
    lava3 = End(130, 110, 140, 70, canvas, 'red', player)
    end = End(210, 74, 225, 110, canvas, 'blue', player)
    while True:
        player.draw()
        platform2.draw()
        if lava.draw() == True or lava2.draw() == True or lava3.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(lava3.id)
            lvl6()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(end.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(lava3.id)
            lvl7()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl7():
    platform = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform2 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform6 = Platform(-60, -50, -40, 200, canvas, "black")
    platform7 = Platform(-120, -235, -140, -50, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    end = End(210, 64, 225, 110, canvas, 'blue', player)

    while True:
        player.draw()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform6.id)
            canvas.delete(platform7.id)
            canvas.delete(end.id)
            lvl8()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl8():
    platform = Platform(-80, 50, -20, 55, canvas, "black")
    platform2 = Platform(-150, -170, -100, -175, canvas, "black", 2, 0, 100)
    platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform6 = Platform(-20, 50, 0, -150, canvas, "black")
    platform7 = Platform(225, -150, 230, 0, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    lava = End(-80, 110, 350, 80, canvas, 'red', player)
    lava2 = End(100, -100, 105, 40, canvas, 'red', player)
    end = End(175, 26, 200, -10, canvas, 'blue', player)

    while True:
        player.draw()
        platform2.draw()
        if lava.draw() == True or lava2.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform6.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(end.id)
            lvl8()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform6.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(end.id)
            lvl9()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl9():
    platform = Platform(-65, 80, 0, 85, canvas, "black", 2, 0, 50)
    platform2 = Platform(-150, -225, 100, -230, canvas, 'black')
    platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform6 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform7 = Platform(10000, -115, 10000, -120, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    portal1 = Portal(player, 300, 310, 325, 335, 0, 50, 25, 75, canvas, "light blue")
    portal2 = Portal(player, 300, 40, 325, 65, 425, 40, 450, 65, canvas, "green")
    lava = End(-70, 100, -60, 75, canvas, 'red', player)
    lava2 = End(-70, 100, 200, 200, canvas, 'red', player)
    lava3 = End(-10, -230, 30, -235, canvas, 'red', player)
    end = End(220, -100, 250, -136, canvas, 'blue', player)

    while True:
        player.draw()
        platform.draw()
        if portal1.check() == True:
            portal_coords2 = portal1.canvas.coords(portal1.id2)
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(lava3.id)
            canvas.delete(end.id)
            canvas.delete(portal1.id)
            canvas.delete(portal2.id)
            canvas.delete(portal1.id2)
            canvas.delete(portal2.id2)
            platform = Platform(-65, 80, 0, 85, canvas, "black", 2, 0, 50)
            platform2 = Platform(-150, -225, 100, -230, canvas, 'black')
            platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform6 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform7 = Platform(10000, -115, 10000, -120, canvas, 'black')        
            player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7, portal_coords2[0], portal_coords2[1], portal_coords2[2], portal_coords2[3])
            portal1 = Portal(player, 300, 310, 325, 335, 0, 50, 25, 75, canvas, "light blue")
            portal2 = Portal(player, 300, 40, 325, 65, 425, 40, 450, 65, canvas, "green")
            lava = End(-70, 100, -60, 75, canvas, 'red', player)
            lava2 = End(-70, 100, 200, 200, canvas, 'red', player)
            lava3 = End(-10, -230, 30, -235, canvas, 'red', player)
            end = End(220, -100, 250, -136, canvas, 'blue', player)
        if portal2.check() == True:
            portal_coords2 = portal1.canvas.coords(portal2.id2)
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(lava3.id)
            canvas.delete(end.id)
            canvas.delete(portal1.id)
            canvas.delete(portal2.id)
            canvas.delete(portal1.id2)
            canvas.delete(portal2.id2)
            platform = Platform(-65, 80, 0, 85, canvas, "black", 2, 0, 50)
            platform2 = Platform(-150, -225, 100, -230, canvas, 'black')
            platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform6 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform7 = Platform(10000, -115, 10000, -120, canvas, 'black')        
            player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7, portal_coords2[0], portal_coords2[1], portal_coords2[2], portal_coords2[3])
            portal1 = Portal(player, 300, 310, 325, 335, 0, 50, 25, 75, canvas, "light blue")
            portal2 = Portal(player, 300, 40, 325, 65, 425, 40, 450, 65, canvas, "green")
            lava = End(-70, 100, -60, 75, canvas, 'red', player)
            lava2 = End(-70, 100, 200, 200, canvas, 'red', player)
            lava3 = End(-10, -230, 30, -235, canvas, 'red', player)
            end = End(220, -100, 250, -136, canvas, 'blue', player)
        if lava.draw() == True or lava2.draw() == True or lava3.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(lava3.id)
            canvas.delete(end.id)
            canvas.delete(portal1.id)
            canvas.delete(portal2.id)
            canvas.delete(portal1.id2)
            canvas.delete(portal2.id2)
            lvl9()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(lava2.id)
            canvas.delete(lava3.id)
            canvas.delete(end.id)
            canvas.delete(portal1.id)
            canvas.delete(portal2.id)
            canvas.delete(portal1.id2)
            canvas.delete(portal2.id2)
            lvl10()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
def lvl10():
    platform = Platform(-20, -50, 45, -55, canvas, "black", 2, 0, 40)
    platform2 = Platform(150, -50, 210, -55, canvas, 'black', 2, 0, 20)
    platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
    platform6 = Platform(-100, 110, -40, -150, canvas, "black")
    platform7 = Platform(-125, -235, -40, -50, canvas, 'black')
    player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7)
    portal1 = Portal(player, 475, 150, 450, 175, 250, 325, 225, 300, canvas, "light blue")
    lava = End(-40, -40, 500, -35, canvas, 'red', player)
    end = End(225, 64, 250, 110, canvas, 'blue', player)
    while True:
        player.draw()
        platform.draw()
        platform2.draw()
        if portal1.check() == True:
            portal_coords2 = portal1.canvas.coords(portal1.id2)
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform6.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(end.id)
            canvas.delete(portal1.id)
            canvas.delete(portal1.id2)
            platform = Platform(-20, -50, 45, -55, canvas, "black", 2, 0, 40)
            platform2 = Platform(150, -50, 210, -55, canvas, 'black', 2, 0, 20)
            platform3 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform4 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform5 = Platform(10000, -115, 10000, -120, canvas, 'black')
            platform6 = Platform(-100, 110, -40, -150, canvas, "black")
            platform7 = Platform(-125, -235, -40, -50, canvas, 'black')       
            player = Player(canvas, "red", platform, platform2, platform3, platform4, platform5, platform6, platform7, portal_coords2[0], portal_coords2[1], portal_coords2[2], portal_coords2[3])
            portal1 = Portal(player, 475, 150, 450, 175, 250, 325, 225, 300, canvas, "light blue")
            lava = End(-40, -40, 500, -35, canvas, 'red', player)
            end = End(225, 64, 250, 110, canvas, 'blue', player)
        if lava.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform6.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(portal1.id)
            canvas.delete(portal1.id2)
            canvas.delete(end.id)
            lvl10()
        if end.draw() == True:
            canvas.delete(player.id)
            canvas.delete(platform.id)
            canvas.delete(platform2.id)
            canvas.delete(platform3.id)
            canvas.delete(platform4.id)
            canvas.delete(platform5.id)
            canvas.delete(platform6.id)
            canvas.delete(platform7.id)
            canvas.delete(lava.id)
            canvas.delete(portal1.id)
            canvas.delete(portal1.id2)
            canvas.delete(end.id)
            canvas.create_text(300, 120, text='You Win!!', font=('Times New Roman', 50))
            lvl10()
        tk.update_idletasks()
        tk.update()
        time.sleep(0.01)
    
    
    

    

lvl1()
